from ..core.vector import EmbeddingVector
from ..core.types import SearchResult

trait VectorIndex:
    fn insert(inout self, vector: EmbeddingVector) raises: ...
    fn search(self, query: EmbeddingVector, k: Int) raises -> List[SearchResult]: ...
    fn remove(inout self, id: UInt64) raises: ...
    fn size(self) -> Int: ...
    fn dimension(self) -> Int: ...
